### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by mikemciver** [Dryopes/OpenCL-Examples#1]
C++/OpenCL novice is attempting to build with OpenCL 2.0 ...

3 instances of ...
Error	1	error C4996: 'clCreateSampler': was declared deprecated	c:\program files (x86)\amd app sdk\3.0\include\cl\cl.hpp	4245	1	CLPlatformsDevices

Unsuccessfully tried various combinations from here ...
http://stackoverflow.com/questions/34359925/empty-opencl-program-throws-deprecation-warning  
and here
https://forums.khronos.org/showthread.php/9545-Intel-OpenCL-2-0-and-c-bindings-problem

---------------------------------------------------------------------------------------------------

6 instances of ...
Error	4	error C2661: 'cl::Buffer::Buffer' : no overloaded function takes 6 arguments	..\host.cpp	51	1	CLPlatformsDevices

cl::Buffer aBuffer(context, aMatrix.begin(), aMatrix.end(), true, false, &error);
Fixed by removing "context".

---------------------------------------------------------------------------------------------------

Warning	9	warning C4018: '<' : signed/unsigned mismatch	..\clplatforms.cpp	17	1	CLPlatformsDevices

return index >= 0 && index < ids.size() ? ids[index] : nullptr;
Fixed with ... static_cast<int>(ids.size())
